---
# systemd handlers

- name: refresh systemd(8) configuration
  systemd:
    daemon_reload: yes

- name: restart systemd-journald(8) daemon
  systemd:
    name: systemd-journald.service
    state: restarted
