---
# apache2 handlers

- name: restart "apache2"
  service: >
    name=apache2
    state=restarted

- name: reload "apache2"
  service: >
    name=apache2
    state=reloaded

- name: reload "apache2" (graceful)
  command: apache2ctl graceful
  listen: SSL certificates updated
