---
# net-base tasks

- name: configure hostname
  tags:
    - networking
    - hostname
  hostname: >
    name="{{ inventory_hostname_short }}"
  when: "ansible_distribution != 'OpenBSD' and ansible_virtualization_type != 'lxc'"
