---
# apache2 tasks

- name: install packages for Apache 2
  tags:
    - apache
    - packages
  apt:
    state: present
    name: [
      'apache2',
      'apache2-utils',
      'apachetop',
    ]
  notify:
    - restart "apache2"

- name: ensure service "apache2" is enabled and started
  tags:
    - apache
    - services
  service: >
    enabled=yes
    name=apache2
    state=started
