---
# apache2-php5 tasks

- name: check if "php5-apcu" package exists
  tags:
    - apache
    - packages
  shell: apt-cache search php5-apcu | grep "^php5-apcu -" >/dev/null
  check_mode: no
  register: php5_apcu_is_available
  failed_when: php5_apcu_is_available.rc > 1
  changed_when: no

- name: install packages for Apache 2 with PHP 5
  tags:
    - apache
    - packages
  apt:
    state: present
    name: [
      'libapache2-mod-php5',
      'php5',
      'php5-cli',
      'php5-mysql',
    ]
  notify:
    - restart "apache2"

- name: install "php5-apcu" cache
  tags:
    - apache
    - packages
  apt: >
    state=present
    name=php5-apcu
  notify:
    - restart "apache2"
  when: php5_apcu_is_available.rc == 0

- name: install "php-apc" cache
  tags:
    - apache
    - packages
  apt: >
    state=present
    name=php-apc
  notify:
    - restart "apache2"
  when: php5_apcu_is_available.rc != 0

- name: ensure service "apache2" is enabled and started
  tags:
    - apache
    - services
  service: >
    enabled=yes
    name=apache2
    state=started
