---
# postfix tasks

# Set Debconf to not configure Postfix at all:
- name: configure debconf(1) to not configure Postfix
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/main_mailer_type
    value="No configuration"
    vtype=select

- name: install "postfix" package
  tags:
    - mail
    - packages
    - postfix
  apt: >
    state=installed
    name=postfix

- name: setup "/etc/mailname"
  tags:
    - mail
    - postfix
  template: >
    dest=/etc/mailname
    group=root
    mode=0644
    owner=root
    src=mailname.j2
  notify:
    - restart "postfix"

- name: set Posfix "myorigin"
  tags:
    - mail
    - postfix
  lineinfile: >
    dest=/etc/postfix/main.cf
    group=root
    line="myorigin = /etc/mailname"
    mode=0644
    owner=root
    regexp="^myorigin"
  notify:
    - restart "postfix"

- name: set Posfix "myhostname"
  tags:
    - mail
    - postfix
  lineinfile: >
    dest=/etc/postfix/main.cf
    group=root
    line="myhostname = {{ postfix_mailname }}"
    mode=0644
    owner=root
    regexp="^myhostname"
  notify:
    - restart "postfix"

- name: set Posfix "mydestination"
  tags:
    - mail
    - postfix
  lineinfile: >
    dest=/etc/postfix/main.cf
    line="mydestination = {{ postfix_mailname }}, localhost"
    regexp="^mydestination"
  notify:
    - restart "postfix"

- name: set Posfix "inet_interfaces"
  tags:
    - mail
    - postfix
  lineinfile: >
    dest=/etc/postfix/main.cf
    line="inet_interfaces = {{ postfix_interfaces }}"
    regexp="^inet_interfaces"
  notify:
    - restart "postfix"

- name: set Posfix "relayhost"
  tags:
    - mail
    - postfix
  lineinfile: >
    dest=/etc/postfix/main.cf
    line="relayhost = {{ smtp_relay_host }}"
    regexp="^relayhost"
  notify:
    - restart "postfix"

- name: ensure service "postfix" is enabled and started
  tags:
    - mail
    - postfix
    - services
  service: >
    enabled=yes
    name=postfix
    state=started
