---
# postfix tasks

- name: 'debconf(1): configure Postfix as "Satellite system"'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/main_mailer_type
    value="Satellite system"
    vtype=select
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set system mail name'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/mailname
    value="{{ postfix_mailname }}"
    vtype=string
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set SMTP relay host'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/relayhost
    value="{{ smtp_relay_host }}"
    vtype=string
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set root and postmaster recipient'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/root_address
    value="{{ postfix_root_address }}"
    vtype=string
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set other destinations to accept mail for'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/destinations
    value="{{ postfix_destinations }}"
    vtype=string
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set local networks'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/mynetworks
    value="{{ postfix_local_networks }}"
    vtype=string
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set mailbox size limit'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/mailbox_limit
    value="{{ postfix_mailbox_limit }}"
    vtype=string
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set local address extension character'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/recipient_delim
    value="{{ postfix_recipient_delim }}"
    vtype=string
  notify:
    - update "postfix" configuration

- name: 'debconf(1): set internet protocols to use'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/protocols
    value="{{ postfix_protocols }}"
    vtype=select
  notify:
    - update "postfix" configuration

- name: 'debconf(1): configure synchronous updates on mail queue'
  tags:
    - debconf
    - mail
    - postfix
  debconf: >
    name=postfix
    question=postfix/chattr
    value="{{ postfix_sync_updates }}"
    vtype=boolean
  notify:
    - update "postfix" configuration

- name: install "postfix" package
  tags:
    - mail
    - packages
    - postfix
  apt: >
    state=installed
    name=postfix

- name: setup "/etc/mailname"
  tags:
    - mail
    - postfix
  template: >
    dest=/etc/mailname
    group=root
    mode=0644
    owner=root
    src=mailname.j2
  notify:
    - restart "postfix"

- name: set Posfix "myorigin"
  tags:
    - mail
    - postfix
  lineinfile: >
    dest=/etc/postfix/main.cf
    group=root
    line="myorigin = /etc/mailname"
    mode=0644
    owner=root
    regexp="^myorigin"
  notify:
    - restart "postfix"

- name: set Posfix "inet_interfaces"
  tags:
    - mail
    - postfix
  lineinfile: >
    dest=/etc/postfix/main.cf
    line="inet_interfaces = {{ postfix_interfaces }}"
    regexp="^inet_interfaces"
  notify:
    - restart "postfix"

- name: ensure service "postfix" is enabled and started
  tags:
    - mail
    - postfix
    - services
  service: >
    enabled=yes
    name=postfix
    state=started
