---
# git-configscripts handlers

- name: install "ConfigScripts" for "root" and system
  shell: make install
  args:
    chdir: /usr/local/src/ConfigScripts

- name: install "ConfigScripts" for users
  shell: su {{ item }} -c "make install"
  args:
    chdir: /usr/local/src/ConfigScripts
  with_items: git_configscripts_users
  when: item != ""
