---
# handlers file for postgresql-server

- name: reload PostgreSQL daemon
  service: >
    name=postgresql
    state=reloaded

- name: restart PostgreSQL daemon
  service: >
    name=postgresql
    state=restarted
