---
# tasks file for docker-engine

- name: install "apt-transport-https" and "ca-certificates"
  tags:
    - docker
    - packages
  apt:
    name: [
      'apt-transport-https',
      'ca-certificates',
    ]
    state: present
  when: docker_apt_repository.startswith("https://")

- name: install docker.io repository GnuPG key
  tags:
    - docker
    - packages
  copy: >
    dest=/etc/apt/trusted.gpg.d/
    group=root
    mode=0644
    owner=root
    src=docker.gpg
  notify:
    - update APT repositories

- name: install docker.io repository configuration
  tags:
    - docker
    - packages
  template: >
    dest=/etc/apt/sources.list.d/docker.list
    group=root
    mode=0644
    owner=root
    src=docker.list.j2
  notify:
    - update APT repositories

- meta: flush_handlers
  tags:
    - apt

- name: install "docker-engine"
  tags:
    - apt
    - docker
    - packages
  apt: >
    name=docker-engine
    state=present

- name: setup "/etc/docker/daemon.json" file
  tags:
    - docker
  template: >
    dest=/etc/docker/daemon.json
    group=root
    mode=0600
    owner=root
    src=daemon.json.j2
  notify:
    - reload Docker
