---
# git-backup-script

- name: install "rsync" and "make"
  tags:
    - packages
  apt: >
    state=installed
    name={{ item }}
  with_items:
    - rsync
    - make

- name: clone "backup-script" GIT repository
  tags:
    - git
    - source
    - backup
  git: >
    accept_hostkey=True
    dest=/usr/local/src/backup-script
    repo={{ git_backup_script_repository }}
    update=yes
  notify:
    - install "backup-script"
