---
# handlers file for os-base

- name: "reload systemd daemon"
  tags:
    - packages
    - systemd
  command: systemctl daemon-reload
  when: "ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'"
