---
# tasks file for postgresql-server

- name: create LVM LV and file system for PostgreSQL data
  tags:
    - postgresql
    - fs
  include_role:
    name: lvm-lv
  vars:
    lvm_vg: "{{ postgresql_server_vg }}"
    lvm_lv_name: "{{ postgresql_server_lv_name }}"
    lvm_lv_size: "{{ postgresql_server_lv_size }}"
    lvm_lv_mountpoint: "/var/lib/postgresql"
  when: postgresql_server_vg != "" and postgresql_server_lv_name != ""

- name: install PostgreSQL {{ postgresql_major }} packages for client and server
  tags:
    - packages
    - postgresql
  apt: >
    state=installed
    name={{ item }}
  with_items:
    - postgresql-{{ postgresql_major }}
