---
# tasks file for postgresql-server

- name: create LVM LV and file system for PostgreSQL data
  tags:
    - postgresql
    - fs
  include_role:
    name: lvm-lv
  vars:
    lvm_vg: "{{ postgresql_server_vg }}"
    lvm_lv_name: "{{ postgresql_server_lv_name }}"
    lvm_lv_size: "{{ postgresql_server_lv_size }}"
    lvm_lv_mountpoint: "/var/lib/postgresql"
  when: postgresql_server_vg|length > 0 and postgresql_server_lv_name|length > 0

- name: install PostgreSQL {{ postgresql_major }} packages for client and server
  tags:
    - packages
    - postgresql
  apt: >
    state=present
    name=postgresql-{{ postgresql_major }}

- name: ensure service "postgresql" is enabled and started
  tags:
    - services
    - postgres
    - postgresql
  service: >
    enabled=yes
    name=postgresql
    state=started
