---
# tasks file for debian-base

- name: install common packages
  tags:
    - packages
  apt: >
    state=installed
    name={{ item }}
  with_items:
    - bash-completion
    - busybox-static
    - ca-certificates
    - curl
    - debconf-utils
    - etckeeper
    - git
    - htop
    - less
    - lsb-base
    - lsb-release
    - psmisc
    - net-tools
    - screen
    - sudo
    - telnet-ssl
    - vim

- name: install Linux kernel packages (amd64)
  tags:
    - packages
  apt: >
    state=installed
    name=linux-image-amd64
  when: "ansible_architecture == 'x86_64'"

- name: install Linux kernel packages (i386)
  tags:
    - packages
  apt: >
    state=installed
    name=linux-image-686-pae
  when: "ansible_architecture == 'i386'"
