---
# tasks file for debian-base

- name: install common packages
  tags:
    - packages
  apt:
    state: present
    name: [
      'bash-completion',
      'ca-certificates',
      'curl',
      'debconf-utils',
      'etckeeper',
      'git',
      'htop',
      'less',
      'lsb-base',
      'lsb-release',
      'psmisc',
      'net-tools',
      'screen',
      'sudo',
      'vim',
    ]

- name: install common packages for Debian <10
  tags:
    - packages
  apt:
    state: present
    name: [
      'telnet-ssl',
    ]
  when: "ansible_distribution_major_version|int < 10"

- name: install common packages for Debian >= 10
  tags:
    - packages
  apt:
    state: present
    name: [
      'telnet',
    ]
  when: "ansible_distribution_major_version|int >= 10"

- name: install common packages (non Proxmox-VE hosts)
  tags:
    - packages
  apt: >
    state=present
    name=busybox-static
  when: "ansible_kernel.find('pve') < 1"

- name: install Linux kernel packages (amd64; non Proxmox-VE hosts, non OpenVZ guest)
  tags:
    - packages
  apt: >
    state=present
    name=linux-image-amd64
  when: "ansible_architecture == 'x86_64' and ansible_kernel.find('pve') < 1 and ansible_virtualization_type != 'openvz'"

- name: install Linux kernel packages (i386; non Proxmox-VE hosts, non OpenVZ guest)
  tags:
    - packages
  apt: >
    state=present
    name=linux-image-686-pae
  when: "ansible_architecture == 'i386' and ansible_kernel.find('pve') < 1 and ansible_virtualization_type != 'openvz'"
