---
# tasks file for linux-zfs

- name: remove outdated "ZFS on Linux" repository configuration
  tags:
    - zfs
    - packages
  file: >
    name={{ item }}
    state=absent
  with_items:
    - /etc/apt/trusted.gpg.d/zfsonlinux.gpg
    - /etc/apt/sources.list.d/zfsonlinux.list
  notify:
    - update APT repositories

- meta: flush_handlers
  tags:
    - zfs
    - packages

- name: install ZFS packages
  tags:
    - packages
    - zfs
  apt: >
    state=installed
    name=zfsutils

- name: setup /usr/local/sbin/zpool-scrub.sh file
  tags:
    - zfs
  template: >
    dest=/usr/local/sbin/zpool-scrub.sh
    group=root
    mode=0755
    owner=root
    src=zpool-scrub.sh.j2

- name: setup /etc/cton.d/zpool-scrub file
  tags:
    - cron
    - zfs
  template: >
    dest=/etc/cron.d/zpool-scrub
    group=root
    mode=0644
    owner=root
    src=cron.d_zpool-scrub.j2
